### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by chrissschin** [chrissschin/country-n-cap#1]
# features
- [x]  **Api** ( M )
  - [x] general get request ( M )
  - [x] country info ( M )
  - [x] put commas into numbers ( s )
  - [x] link info from country list into country detail ( M )
  - [x] get neighbors info ( M )
- [x] **Views Templating** 
  - [x] Index View ( s )
  - [x] Countries List ( s )
  - [x] Country Detail ( s )
- [ ] **Animations** ( s )
  - [ ] Create loading state and timeout ( s )
  - [ ] Smooth Transitions of views  ( s )
- [ ] **Gulp** ( s )
  - [ ] concatenate all files into a folder.
